@startuml
skinparam class {
  Padding 5
  AttributeFontSize 14
  MethodFontSize 14
}
top to bottom direction

package client as CLI {
    together {
        package command {
            class ClientCommandDispatcher {
                +handle(line : String) : CompletableFuture<Void>
            }
        }

        package tui as TUI {
            abstract class TerminalUI {
                +addInputHandler(handler : TerminalInputHandler) : void
                +start() : void
                +stop() : void
                +setPrompt(prompt : RichString) : void
                +setStatus(status : RichString) : void
                +println(message : TerminalMessage) : void
            }

            interface TerminalInputHandler {
                +handle(input : String) : CompletableFuture<Void>
            }

            TerminalUI ..> TerminalInputHandler : inputHandlers
        }
    }

    package dcc as CLI_DCC {

        interface DCCClientEventListener {
            +onEvent(event : DCCClientEvent) : void
        }

        class DCCDownloader {
            +start() : void
            +cancel() : void
        }

        class DCCUploader {
            +start() : void
            +cancel() : void
        }

        DCCDownloader ..> DCCClientEventListener
        DCCUploader ..> DCCClientEventListener
    }


    class IRCClientState <<aggregate>> {}

    class IRCClientEngine {
        +onDisconnect(connection: IRCConnection) : void
        +accept(command : ClientCommand) : CompletableFuture<Void>
        +receive(connection: IRCConnection, message : String) : void
        +start() : void
        +close() : void
        +onEvent(event : DCCClientEvent) : void
    }
}

package network as NET {

    interface IRCDisconnectHandler {
        +onDisconnect(connection : IRCConnection) : void
    }

    interface IRCIngressHandler {
        +receive(connection : IRCConnection, line : String) : void
    }

    class IRCConnection {
        +IRCConnection(socket : Socket)
        +addIngressHandler(handler : IRCIngressHandler) : void
        +addShutdownHandler(handler : IRCDisconnectHandler) : void
        +offer(line : String) : boolean
        +start() : void
        +close() : void
        +closeDeferred() : CompletableFuture<Void>
        +getHostAddress() : String
        +isClosed() : boolean
    }

    class Acceptor {
        +start() : int
        +close() : void
    }

    interface Dispatcher {
        +dispatch(socket : Socket) : boolean
    }

    Acceptor .right.> Dispatcher
    IRCConnection ..> IRCIngressHandler : ingressHandlers
    IRCConnection ..> IRCDisconnectHandler : shutdownHandlers
}

package server as SRV {
    package dcc {
        interface DCCServerEventListener {
            +onEvent(event : DCCServerEvent) : void
        }

        class DCCRelayEngine {
            +addListener(listener : DCCServerEventListener) : void
            +openForReceiver(token : UUID) : CompletableFuture<Integer>
            +openForSender(token : UUID) : CompletableFuture<Integer>
            +cancel(token : UUID) : void
            +close() : void
        }

        DCCRelayEngine ..> DCCServerEventListener : listeners
    }

    package state {
        class ServerState <<aggregate>>
    }

    class IRCServerEngine {
        +accept(socket : Socket) : boolean
        +onDisconnect(connection : IRCConnection) : void
        +receive(connection : IRCConnection, line : String) : void
        +close() : void
        +onEvent(event : DCCServerEvent) : void
    }
}

Dispatcher -[hidden]down-> IRCConnection
CLI -[hidden]right-> SRV

ClientCommandDispatcher ..> TerminalUI : print errors
ClientCommandDispatcher .right.> IRCClientEngine : send commands

IRCClientEngine ..> TerminalUI : print messages
IRCClientEngine ..> IRCConnection : send messages
IRCClientEngine ..> IRCClientState
IRCClientEngine ..> DCCDownloader : receive dcc
IRCClientEngine ..> DCCUploader : send dcc

IRCServerEngine ..> DCCRelayEngine : proxy dcc
IRCServerEngine ..> ServerState
IRCServerEngine ..> IRCConnection : send messages


@enduml
