@startuml
skinparam componentSpacing 40
skinparam nodesep 20
skinparam ranksep 10

component "TerminalUI" as tui {
    agent "TerminalUI-Loop" <<thread>> as tui_loop
}
agent "terminal" <<stdio>> as terminal
agent "stty" <<native>> as stty
component "ClientCommandParser" as command_parser
queue "Command Queue" as command_queue
component "IRCClientEngine" as engine {
    agent "IRCClientEngine-Ingress" <<thread>> as engine_reader
    agent "IRCClientEngine-Egress" <<thread>> as engine_writer
}
cloud "IRC Server" as server

terminal --> tui_loop : stdin
tui --> terminal : draw tui
stty <-- tui : terminal mode\n(unix only)
tui_loop --> command_parser : Pass user input lines
command_parser -right-> command_queue : Enqueue commands
engine_writer --> command_queue : Dequeue commands
server <-- engine_writer : Publish Message
server --> engine_reader : Receive Message
engine_reader --> tui : Print Messages
@enduml
