public sealed interface ClientCommand extends ArgsProperties
    permits ClientCommandConnect,
        ClientCommandExit,
        ClientCommandHelp,
        ClientCommandJoin,
        ClientCommandKick,
        ClientCommandMode,
        ClientCommandMsg,
        ClientCommandMsgCurrent,
        ClientCommandNick,
        ClientCommandNotice,
        ClientCommandOper,
        ClientCommandPart,
        ClientCommandQuit,
        ClientCommandTopic {}
